### ISSUE TITLE
Data-атрибуты

### ISSUE THREAD

**Issue by MorganaLF** [Nelliza/slider#11]
В jQuery обертке надо реализовать поддержку data-атрибутов  для задания настроек, т.к. это best practices по созданию jQuery плагинов.

**Comment by MorganaLF** [comment]
А для чего потребовался метод removeDataAttributes()? Мне кажется, после создания слайдера дата-атрибуты не должны меняться, это ведь изначальные настройки

**Comment by Nelliza** [comment]
> А для чего потребовался метод removeDataAttributes()? Мне кажется, после создания слайдера дата-атрибуты не должны меняться, это ведь изначальные настройки

У меня неправильно был спроектирован метод обновления приложения у контроллера - при изменении настроек в полях панели (размер шага, наличие/отсутствие шкалы и т.д.) заново создавались инстансы MVC-классов, и получалось, что если не удалить data-атрибуты, слайдер отображался с первоначально заданными в этих атрибутах настройками. Внесла исправления, теперь метод removeDataAttributes() действительно лишний )
