### ISSUE TITLE
Правки по замечаниям к другим проектам

### ISSUE THREAD

**Issue by Nelliza** [Nelliza/slider#4]

**Comment by MorganaLF** [comment]
По поводу имен переменных, проверь еще везде, где у тебя встречается e, elem, и т.д.

![Снимок экрана в 2019-08-18 22-58-38](https://user-images.githubusercontent.com/38564412/63229675-c827ef80-c20b-11e9-8316-0e45f067d203.png)

**Comment by Nelliza** [comment]
> По поводу имен переменных, проверь еще везде, где у тебя встречается e, elem, и т.д.

Да, у меня это записано в пункте дел  ) После исправления минимума/максимума займусь этим )

**Comment by Nelliza** [comment]
> По поводу имен переменных, проверь еще везде, где у тебя встречается e, elem, и т.д.

Да, у меня это записано в списке дел, после исправления настроек минимума/максимума займусь этим )

**Comment by MorganaLF** [comment]
Можно закрывать
