### ISSUE TITLE
Model

### ISSUE THREAD

**Issue by MorganaLF** [Nelliza/slider#5]
Сейчас у тебя во вьюхах содержатся настройки, которые должны быть в конфиге модели: `isVertical`, `hasInterval` и т.л. - все это должно лежать в модели, а вью может просто получить модель в качестве аргумента и отрисовывать на основе ее конфига.

**Comment by MorganaLF** [comment]
Дефолтные значения конфига модели также лучше хранить в модели, можно создать отдельный файл и положить все настройки туда, убрать их из `App`

![Снимок экрана в 2019-08-26 23-35-38](https://user-images.githubusercontent.com/38564412/63721616-44e54a00-c85a-11e9-8f4a-bd1e2ac2e4ac.png)

Заодно можно будет избавиться от таких вещей, не просто писать какие-то значения в методах, а брать их из дефолтного конфига (я имею ввиду, что размер шага тут приравнен к единице):

![Снимок экрана в 2019-08-26 23-36-44](https://user-images.githubusercontent.com/38564412/63721723-7d852380-c85a-11e9-8443-f47e8c92618f.png)

**Comment by MorganaLF** [comment]
По названию метода `_checkValue` ожидается, что он проверит и вернет булево значение, но в самом методе происходит не только проверка, но и изменение значения. Поэтому имя метода надо поменять на более подходящее. 
И еще, мне кажется, можно этот метод разбить, сейчас с первого взгляда не понятно, что в нем происходит)

**Comment by MorganaLF** [comment]
Валидация настроек также относится к модели, а не App, это нужно перенести.

**Comment by MorganaLF** [comment]
Вот здесь у тебя противоречие стандартам airbnb, способы приведения к числу указаны здесь:  
https://github.com/airbnb/javascript#coercion--numbers

![Снимок экрана в 2019-09-01 09-37-34](https://user-images.githubusercontent.com/38564412/64072732-96e40080-cc9c-11e9-80c9-90c2da737e23.png)

**Comment by MorganaLF** [comment]
В методе validate очень много вложенных if..else, что делает код трудно читаемым, нельзя ли как-то упростить?) Может быть, например, объявить булевы константы, в которых объединять условия с помощью &&, и так получится избавиться от вложенности?

**Comment by MorganaLF** [comment]
В validate() пока что по-прежнему переусложнено: switch, в котором лежит if, в котором лежит тернарник) Надо еще подумать, как улучшить, ишью пока не закрываю)

**Comment by MorganaLF** [comment]
Вот такие моменты выглядят немного подозрительно:

![Снимок экрана в 2019-09-09 21-14-22](https://user-images.githubusercontent.com/38564412/64555833-dc609780-d346-11e9-858c-80d04ce19771.png)

Обязательно ли хранить эти значения в массивах? Может быть, нагляднее было бы, если бы каждому из них соответствовало свое поле объекта?

**Comment by Nelliza** [comment]
> Вот такие моменты выглядят немного подозрительно:
> 
> ![Снимок экрана в 2019-09-09 21-14-22](https://user-images.githubusercontent.com/38564412/64555833-dc609780-d346-11e9-858c-80d04ce19771.png)
> 
> Обязательно ли хранить эти значения в массивах? Может быть, нагляднее было бы, если бы каждому из них соответствовало свое поле объекта?

Текущие значения я храню в массиве для их сортировки в случае, если изначально будет задано первое значение больше второго, чтобы поменять их местами

**Comment by MorganaLF** [comment]
По индексам создала отдельное ишью)
