### ISSUE TITLE
View

### ISSUE THREAD

**Issue by MorganaLF** [Nelliza/slider#8]
Метод `init`, мне кажется, лучше разбить на более мелкие методы, соответствующие инициализации отдельных компонентов.

**Comment by MorganaLF** [comment]
Вот здесь, поскольку величина отступа не меняется, лучше в css создать класс и добавлять его.

![Снимок экрана в 2019-09-01 10-01-06](https://user-images.githubusercontent.com/38564412/64072925-b2043f80-cc9f-11e9-8452-5b0c0513696b.png)

**Comment by MorganaLF** [comment]
Обработка браузерных событий должна быть в самом классе, если тебе надо в главную вьюху передать какие-то данные, например, на какое значение переместился бегунок, то можно оповестить ее при помощи observer. 

![Снимок экрана в 2019-09-01 10-05-19](https://user-images.githubusercontent.com/38564412/64072977-669e6100-cca0-11e9-9e4e-08d47253c544.png)

**Comment by MorganaLF** [comment]
`showOrientation` не совсем корректное название, по нему кажется, что сейчас будет показано что-то вроде "у слайдера вертикальное расположение") Здесь, скорее, `setOrientation`

**Comment by MorganaLF** [comment]
Вот здесь и в аналогичных случаях лучше писать `this.isVertical ? ... : ...`, без отрицания, так лучше читается условие. Отрицание более уместно, если тебе нужно, например, сразу выйти из цикла, когда условие не соблюдено, или если у тебя только одно условие. 

![Снимок экрана в 2019-09-01 10-32-56](https://user-images.githubusercontent.com/38564412/64073279-2e991d00-cca4-11e9-9420-10c1673acdf9.png)

**Comment by MorganaLF** [comment]
По классам `ViewPointer` и` ViewThumb`:

По идее, один класс = один компонент, если тебе надо создать два компонента, то это делается путем создания двух экземпляров классов, то есть ты в главной вьюхе дважды будешь инициализировать ViewPointer, если тебе их нужно два .

**Comment by MorganaLF** [comment]
И еще не совсем понятно, почему tracker оказался в классе ViewThumb, если ты решила его не выделять в отдельный класс, то хотя бы в главную вьюху его поместить.

**Comment by MorganaLF** [comment]
Вроде переносили демо в отдельную папку, но инициализация демки почему-то оказалась во вьюхе плагина) 
Смотри, представь, что кому-то потребуется твой плагин для использования в проекте. Для того, чтобы подключить его к проекту, нужны будут только те компоненты, которые относятся к самому слайдеру. А тут еще и инициализация демо потянется за собой, которая совсем не нужна. 

![Снимок экрана в 2019-09-06 20-09-07](https://user-images.githubusercontent.com/38564412/64446716-357bc180-d0e2-11e9-876d-8d4dcbf0be6a.png)

С демкой ты делаешь то же самое, что и в предыдущем проекте: класс в одном файле, отдельно файл с инициализацией, все это лежит в папке компонента demo.

**Comment by MorganaLF** [comment]
Еще заметила, что ты во вьюхах иногда для рассчетов берешь значения из css. Такие значения не всегда могут давать корректные результаты и лучше использовать для рассчетов координаты.

![Снимок экрана в 2019-09-06 20-20-55](https://user-images.githubusercontent.com/38564412/64447354-dc149200-d0e3-11e9-8d72-a0b9aedae740.png)

**Comment by MorganaLF** [comment]
По DemoView еще не всё. Это должен быть совершенно независимый компонент. Ни App, ни MainView ничего о нем не должны знать. 

Если тебе нужны события плагина, то плагин их просто генерирует, а демо слушает их и что-то делает в зависимости от этих событий. Точно так же, как представь, что на сайте был бы какой-то другой совершенно не относящийся к слайдеру компонент, которому надо было бы что-то делать в зависимости от событий слайдера. 

А обратная связь - когда в демке что-то поменялось (пользователь что-то ввел в инпут например) и надо обновить вью, должна осуществляться при помощи публичных методов плагина.

**Comment by Nelliza** [comment]
> По `DemoView` еще не всё. Это должен быть совершенно независимый компонент. Ни `App`, ни `MainView` ничего о нем не должны знать.
> А инициализацию DemoView ты делаешь так, как в прошлом проекте ты делала с блоками. У тебя в одном файле лежал класс, а другой файл был init.

Не очень понимаю этот момент, если честно ) Сейчас я инициализирую демо-панель с настройками, которые получаю из конфига модели, а если я буду отдельно инициализировать ее, то не могу придумать, откуда брать тогда все эти значения (размер шага, min/max значения и т.д.)

**Comment by Nelliza** [comment]
> А инициализацию DemoView ты делаешь так, как в прошлом проекте ты делала с блоками. У тебя в одном файле лежал класс, а другой файл был init.

Не очень понимаю этот момент, если честно ) Сейчас я инициализирую демо-панель с настройками, которые получаю из конфига модели, а если я буду отдельно инициализировать ее, то не могу придумать, откуда брать тогда все эти значения (размер шага, min/max значения и т.д.)

> По `DemoView` еще не всё. Это должен быть совершенно независимый компонент. Ни `App`, ни `MainView` ничего о нем не должны знать.

А контроллер может знать о демо-вьюхе? Если так, то можно без проблем передать конфиг модели демо-вьюхе через контроллер, таким образом основная вьюха и демо-вьюха будут независимыми друг от друга. Но создание инстанса демо-вьюхи, как ни крути, будет происходить в App, что мне кажется приемлемым, честно говоря )

**Comment by Nelliza** [comment]
> А инициализацию DemoView ты делаешь так, как в прошлом проекте ты делала с блоками. У тебя в одном файле лежал класс, а другой файл был init.

Да, не очень понимаю этот момент ) Сейчас я инициализирую демо-панель с настройками, которые получаю из конфига модели, а если я буду отдельно инициализировать ее, то не могу придумать, откуда брать тогда все эти значения (размер шага, min/max значения и т.д.)

> По `DemoView` еще не всё. Это должен быть совершенно независимый компонент. Ни `App`, ни `MainView` ничего о нем не должны знать.

А контроллер может знать о демо-вьюхе? Если так, то можно без проблем передать конфиг модели демо-вьюхе через контроллер, таким образом основная вьюха и демо-вьюха будут независимыми друг от друга. Но создание инстанса демо-вьюхи, как ни крути, будет происходить в App, что мне кажется приемлемым, честно говоря )

**Comment by MorganaLF** [comment]
Нет, ничего из того, что у тебя лежит в папке `plugin`, не должно знать о демо-вьюхе)

Вот смотри, представь, что тебе надо использовать этот плагин в проекте ui-kit. Ты берешь все, что лежит в папке `plugin`. `DemoView `тебе в ui-kite не нужно, ты этот компонент не берешь. В итоге у тебя ничего не работает, поскольку у тебя в плагине идет обращение к классу `DemoView`, которого нет. 

Тебе придется выпиливать из файлов плагина все, что связано с вьюхой демо. А такого быть не должно, плагин он на то и плагин, что ты его подключила и вовнутрь не лезешь)

**Comment by Nelliza** [comment]
> Тебе придется выпиливать из файлов плагина все, что связано с вьюхой демо. А такого быть не должно, плагин он на то и плагин, что ты его подключила и вовнутрь не лезешь)

А как мне передать туда провалидированные опции для инпутов?

**Comment by MorganaLF** [comment]
> Сейчас я инициализирую демо-панель с настройками, которые получаю из конфига модели

Тебе эти данные нужны для отображения значений в инпутах? Если для этого, то эти данные можно получать, подписываясь на события модели.

**Comment by MorganaLF** [comment]
Если же что-то изменилось в модели, то контроллер может генерировать событие, например 'changeValue', а DemoView это событие слушает и у себя уже по событию меняет значения инпутов.

**Comment by Nelliza** [comment]
> > Сейчас я инициализирую демо-панель с настройками, которые получаю из конфига модели
> 
> Тебе эти данные нужны для отображения значений в инпутах? Думаю, это лучше сделать при помощи публичных методов, что-то вроде `getStepSize`, `isVerticalOrientation` и т.л. Такие методы предоставляет контроллер, который в свою очередь берет данные из модели.

**Comment by Nelliza** [comment]
Все равно не пойму ) Как демо-вьюха имеет доступ к контроллеру, если не через App?

**Comment by Nelliza** [comment]
> > > Сейчас я инициализирую демо-панель с настройками, которые получаю из конфига модели
> > 
> > 
> > Тебе эти данные нужны для отображения значений в инпутах? Думаю, это лучше сделать при помощи публичных методов, что-то вроде `getStepSize`, `isVerticalOrientation` и т.л. Такие методы предоставляет контроллер, который в свою очередь берет данные из модели.

Все равно не пойму ) Как демо-вьюха имеет доступ к контроллеру, если не через App?

**Comment by Nelliza** [comment]
> Тебе эти данные нужны для отображения значений в инпутах? Думаю, это лучше сделать при помощи публичных методов, что-то вроде `getStepSize`, `isVerticalOrientation` и т.л. Такие методы предоставляет контроллер, который в свою очередь берет данные из модели.

Все равно не пойму ) Как демо-вьюха имеет доступ к контроллеру, если не через App?

**Comment by MorganaLF** [comment]
`DemoView` может общаться с твоим плагином через публичные методы. Публичные методы как раз предназначены для того, чтобы посредством их общаться с компонентами извне. Но он не может инициализироваться в контроллере или апп, То есть он у себя там инициализируется, к нему подключается слайдер, и он у себя уже внутри вызывает методы слайдера. И, кстати, так как это jQuery плагин, то эти методы будут выглядеть примерно так: $('.slider').slider('getCurrentValue');

Да, если у тебя там есть класс App, то придется методы контроллера в него прокидывать, но вообще у меня в слайдере тоже по началу была такая схема, в итоге получалось, что App дублирует Controller и App я вообще удалила.

**Comment by MorganaLF** [comment]
Что-то я у тебя вот этот момент не поняла)

![Снимок экрана в 2019-09-16 15-17-13](https://user-images.githubusercontent.com/38564412/64957208-1b39a480-d895-11e9-9a9e-4e3e27e5b060.png)

Ты здесь подписалась на событие контроллера 'updatePlugin', и вызвала рекурсивно init? Просто у тебя во-первых тут ошибка получается, константа init используется в коде до ее объявления и ее линтер подчеркивает. Ну и может как-то по-другому это написать лучше? 

Например, в `update` вынести инициализацию классов, а внутри `init` вызывать `update`,  а ниже подписываться на контроллер?

**Comment by Nelliza** [comment]
> Ты здесь подписалась на событие контроллера 'updatePlugin', и вызвала рекурсивно init? Просто у тебя во-первых тут ошибка получается, константа init используется в коде до ее объявления и ее линтер подчеркивает. Ну и может как-то по-другому это написать лучше?
> 
> Например, в `update` вынести инициализацию классов, а внутри `init` вызывать `update`, а ниже подписываться на контроллер?

Да, было не комильфо, согласна. Отрефакторила, убрав вообще все функции внутри кода обертки ) Ну и в остальном чуть упростила код.
