### ISSUE TITLE
Именование переменных

### ISSUE THREAD

**Issue by MorganaLF** [Nelliza/slider#9]
Некоторые переменные сейчас не очень информативны:

**MainView.js**

![Снимок экрана в 2019-09-06 19-51-55](https://user-images.githubusercontent.com/38564412/64445748-d74ddf00-d0df-11e9-89f1-ff73167d43e9.png)

Переменная `count `- непонятно, количество чего именно. Тут вообще в целом немного странно реализовано, во-первых, у тебя есть в конфиге поле `hasInterval`, вот вторых, стоит ли туда именно число передавать, может, как раз флага будет достаточно?

![Снимок экрана в 2019-09-06 19-57-25](https://user-images.githubusercontent.com/38564412/64446071-94403b80-d0e0-11e9-9b54-bda91e9b1fff.png)

css, cssValue, lessCss... - здесь можно более конкретные и подходящие названия найти, topOffsetProperty, например. 

Названия событий:

Вьюха не делает ничего со значениями, это работа модели. Значит, события вьюхи не могут именоваться updateValues, в имени события ты описываешь, что в этот момент произошло. 

![Снимок экрана в 2019-09-06 20-00-43](https://user-images.githubusercontent.com/38564412/64446387-598ad300-d0e1-11e9-8464-946c1ce46bb0.png)

**Comment by MorganaLF** [comment]
**Model.js**

Такие имена, как `array`, не рекомендуются стандартами, это ведь не просто массив, он для чего-то конкретного у тебя предназначен) Тут и переменную и имя метода надо поменять

![Снимок экрана в 2019-09-06 20-26-53](https://user-images.githubusercontent.com/38564412/64447727-bc319e00-d0e4-11e9-9e4d-1b5ce81adce8.png)

Если в переменной лежит булев тип, то у нее должно быть соответствующее название, начинающееся с is, has и т.л., это тоже есть в стандартах:

![Снимок экрана в 2019-09-06 20-28-25](https://user-images.githubusercontent.com/38564412/64447846-fbf88580-d0e4-11e9-9487-40731ea96172.png)

**Comment by MorganaLF** [comment]
По поводу событий я, наверное, непонятно объяснила)
Смотри, у тебя во вьюхе есть событие `changeCurrentValues`. Но вьюха никакие values не меняет, в ней их вообще нет, они в модели) Что происходит в тот момент, когда кнопка мыши поднимается? Бегунок перестает двигаться. Вот исходя из этого и стоит именовать событие)

А change values, update values, set values и что угодно другое с values может происходить только в модели) И только модель, соответственно, может генерить такие события.

**Comment by MorganaLF** [comment]
Дальше, что за событие в `MainView`, которое называется `changeCurrentFields`? Во вьюхе плагина никаких полей нет, они есть в DemoView, а значит только DemoView может генерировать такие события.

**Comment by Nelliza** [comment]
> По поводу событий я, наверное, непонятно объяснила)

Нормально ты объяснила, просто я наверное поверхностно уловила суть, чтобы быстрее внести правки )

**Comment by MorganaLF** [comment]
**DemoView**

Вот это не похоже на имена полей ввода) 

![Снимок экрана в 2019-09-16 15-33-06](https://user-images.githubusercontent.com/38564412/64958257-5b9a2200-d897-11e9-9d06-c06c85431ef0.png)

Например, по имени $scale кажется, что в этой переменной лежит элемент шкалы, а не поле ввода. $vertical, $interval - тем более.

**Comment by MorganaLF** [comment]
Название переменной `pixelsPerValue`, а заодно и метода, нуждается в пояснении) Надо что-то более конкретное придумать

![Снимок экрана в 2019-09-16 15-54-40](https://user-images.githubusercontent.com/38564412/64959680-54284800-d89a-11e9-9b01-e233a81458dd.png)

**Comment by MorganaLF** [comment]
Не совсем понятно, для чего у тебя предназначено свойство `$element` в конструкторах классов. По идее это корневой элемент для компонента, а у тебя везде лежит одно и то же значение? В `ScaleView`, например, это скорее `parentElement` должен быть. 

![Снимок экрана в 2019-09-16 16-06-45](https://user-images.githubusercontent.com/38564412/64960677-67d4ae00-d89c-11e9-9d4e-b7e2d3463ed0.png)

**Comment by Nelliza** [comment]
> Немного не по этому ишью вопрос: есть ли необходимость здесь каждый раз через цикл прогонять `offsetValue`? Оно вроде никак не зависит у тебя от цикла.

offsetValue зависит от переменной value, которая увеличивается с каждой итерацией цикла
![1](https://user-images.githubusercontent.com/19621113/64974652-84c5ad00-d8ad-11e9-8d96-e3b7cddd2081.jpg)

**Comment by MorganaLF** [comment]
> offsetValue зависит от переменной value, которая увеличивается с каждой итерацией цикла

Да, точно, не заметила)

**Comment by MorganaLF** [comment]
Я всё-таки еще не соглашусь с твоими названиями) `isVertical`, `hasInterval` и другие подобные наименования подразумевают, что там лежит булево значение: `true` либо `false`. А у тебя там лежат html-элементы. Попробуй в названиях отталкиваться от того, что это поле и для чего оно предназначено.

**Comment by MorganaLF** [comment]
Еще правка по именованиям)

`MainView`, метод `_showTracker` судя по всему не просто показывает трекер, так что надо названием описать, что именно он делает. 

![Снимок экрана в 2019-09-19 21-57-31](https://user-images.githubusercontent.com/38564412/65272937-b8f8d200-db28-11e9-9170-d830c1d8e417.png)
